version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: passmngr
      MYSQL_USER: root
    volumes: ["./data/db:/var/lib/mysql"]
    ports: ["8000:3306"]

  api:
    build: .
    container_name: api
    restart: always
    ports: ["3500:8080"]
    volumes: [".:/app/passmngr"]
    depends_on: ["db"]
